POST http://localhost:5000/api/administrator/car-categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNzU2MDQzLCJleHAiOjE3NjE4NDI0NDN9.GZkDWYZh_U5ujUQ5cHVImUHD_u8BgiGDPvKZbi6ZMt1tvTUPvCTeSP8skq9jFh9K93JysVcBO5g08Fd_7sKF9Q

# {
#     "name":"AUDI",
#     "description": "Audi description",
#     "baseRate": 200000
# }

{
    "name":"Jaguar",
    "description": "Jaguar description",
    "baseRate": 300000
}

### Get all categories
GET http://localhost:5000/api/administrator/car-categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNzU2MDQzLCJleHAiOjE3NjE4NDI0NDN9.GZkDWYZh_U5ujUQ5cHVImUHD_u8BgiGDPvKZbi6ZMt1tvTUPvCTeSP8skq9jFh9K93JysVcBO5g08Fd_7sKF9Q

### Update car categories
PUT http://localhost:5000/api/administrator/car-categories/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNzU2MDQzLCJleHAiOjE3NjE4NDI0NDN9.GZkDWYZh_U5ujUQ5cHVImUHD_u8BgiGDPvKZbi6ZMt1tvTUPvCTeSP8skq9jFh9K93JysVcBO5g08Fd_7sKF9Q

{
    "name":"JAGUAR",
    "description": "Jaguar description",
    "baseRate": 300000
}

### get all Bookings
GET http://localhost:5000/api/administrator/reports/bookings
Content-Type: 'application/json'
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNzU2MDQzLCJleHAiOjE3NjE4NDI0NDN9.GZkDWYZh_U5ujUQ5cHVImUHD_u8BgiGDPvKZbi6ZMt1tvTUPvCTeSP8skq9jFh9K93JysVcBO5g08Fd_7sKF9Q

### get all payments
GET http://localhost:5000/api/administrator/reports/payments
Content-Type: 'application/json'
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNzU2MDQzLCJleHAiOjE3NjE4NDI0NDN9.GZkDWYZh_U5ujUQ5cHVImUHD_u8BgiGDPvKZbi6ZMt1tvTUPvCTeSP8skq9jFh9K93JysVcBO5g08Fd_7sKF9Q