POST http://localhost:5000/api/administrator/car-categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNjQxNDcxLCJleHAiOjE3NjE3Mjc4NzF9.z6ShSxLJ7QrxYUMKY9yqpm2VJRmcY45GtoRTpoZeCCWvu3fZl9O7IfBXOyeSDweMd7JRHFKa19t8-blWNd90hw

{
    "name":"AUDI",
    "description": "Audi description",
    "baseRate": 200000
}

# {
#     "name":"Jaguar",
#     "description": "Jaguar description",
#     "baseRate": 300000
# }

### Get all categories
GET http://localhost:5000/api/administrator/car-categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNTg0NjEzLCJleHAiOjE3NjE2NzEwMTN9.mhpe5LzdakzFIZXT6shTqBzJAkIxsi87HlxhQuaMnsybNj5Tua2bbRR0tOvK4wNcXqHysfzomeg7NgH98ZxoBg

### Update car categories
PUT http://localhost:5000/api/administrator/car-categories/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNTg0NjEzLCJleHAiOjE3NjE2NzEwMTN9.mhpe5LzdakzFIZXT6shTqBzJAkIxsi87HlxhQuaMnsybNj5Tua2bbRR0tOvK4wNcXqHysfzomeg7NgH98ZxoBg

{
    "name":"JAGUAR",
    "description": "Jaguar description",
    "baseRate": 300000
}

### get all Bookings
GET http://localhost:5000/api/administrator/reports/bookings
Content-Type: 'application/json'
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNTg0NjEzLCJleHAiOjE3NjE2NzEwMTN9.mhpe5LzdakzFIZXT6shTqBzJAkIxsi87HlxhQuaMnsybNj5Tua2bbRR0tOvK4wNcXqHysfzomeg7NgH98ZxoBg

### get all payments
GET http://localhost:5000/api/administrator/reports/payments
Content-Type: 'application/json'
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJBRE1JTklTVFJBVE9SIiwiaWF0IjoxNzYxNTg0NjEzLCJleHAiOjE3NjE2NzEwMTN9.mhpe5LzdakzFIZXT6shTqBzJAkIxsi87HlxhQuaMnsybNj5Tua2bbRR0tOvK4wNcXqHysfzomeg7NgH98ZxoBg