POST http://localhost:5000/api/agent/car
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZ2VudCIsInJvbGUiOiJBR0VOVCIsImlhdCI6MTc2MTgyMzk3NCwiZXhwIjoxNzYxOTEwMzc0fQ.LUrBOMHO4PVR8gYg97aNRkRvUUdBjh1-qkjGeW3M5hBVXUQKifwomuB30WoCBHJR46YHpxqGUy5VLtBV-MvntQ


# {
#     "make": "Audi Make",
#     "model": "Audi Model",
#     "manufactureYear": "1983",
#     "registrationNumber": "TZ123456",
#     "status": "available",
#     "rentalRatePerDay": 20000,
#     "category": { "id": 1}
# }

//For duplicate registration number it should be 208
//For no category/non-existing it should be 404
//For no id it should be 400
# {
#     "make": "Audi Make",
#     "model": "Audi Model",
#     "manufactureYear": "1983",
#     "registrationNumber": "TZ123457",
#     "status": "available",
#     "rentalRatePerDay": 20000,
#     "category": {
#         "id": 14
#     }
# }

{
    "make": "Benz Make",
    "model": "Benz Model",
    "manufactureYear": "1999",
    "registrationNumber": "JH123450",
    "status": "available",
    "rentalRatePerDay": 300000,
    "category": { "id": 2}
}

### Get all cars
GET http://localhost:5000/api/agent/cars
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWSVZFSzQxMDAiLCJyb2xlIjoiQUdFTlQiLCJpYXQiOjE3NjE3NTYzMDEsImV4cCI6MTc2MTg0MjcwMX0.oH61PGam9ydjbST7GQ4BBlNeoJzj5UJMJcOkHKrKH3FuTAWzaQqhkF0o4HylVZP49tgPHxBXBpisga7LeCMI6w

### update an existing car
PUT http://localhost:5000/api/agent/car/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZ2VudCIsInJvbGUiOiJBR0VOVCIsImlhdCI6MTc2MTgyMzk3NCwiZXhwIjoxNzYxOTEwMzc0fQ.LUrBOMHO4PVR8gYg97aNRkRvUUdBjh1-qkjGeW3M5hBVXUQKifwomuB30WoCBHJR46YHpxqGUy5VLtBV-MvntQ

{
    "make": "Benz Make",
    "model": "Benz Model",
    "manufactureYear": "1999",
    "registrationNumber": "JH123459",
    "status": "available",
    "rentalRatePerDay": 300000,
    "category": { "id": 2}
}

### Get all bookings
GET http://localhost:5000/api/agent/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWSVZFSzQxMDAiLCJyb2xlIjoiQUdFTlQiLCJpYXQiOjE3NjE3NTYzMDEsImV4cCI6MTc2MTg0MjcwMX0.oH61PGam9ydjbST7GQ4BBlNeoJzj5UJMJcOkHKrKH3FuTAWzaQqhkF0o4HylVZP49tgPHxBXBpisga7LeCMI6w

### Update booking status
PUT http://localhost:5000/api/agent/bookings/1/status?status=booked
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWSVZFSzQxMDAiLCJyb2xlIjoiQUdFTlQiLCJpYXQiOjE3NjE3NTYzMDEsImV4cCI6MTc2MTg0MjcwMX0.oH61PGam9ydjbST7GQ4BBlNeoJzj5UJMJcOkHKrKH3FuTAWzaQqhkF0o4HylVZP49tgPHxBXBpisga7LeCMI6w

### create a payment
POST http://localhost:5000/api/agent/payment/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWSVZFSzQxMDAiLCJyb2xlIjoiQUdFTlQiLCJpYXQiOjE3NjE3NTYzMDEsImV4cCI6MTc2MTg0MjcwMX0.oH61PGam9ydjbST7GQ4BBlNeoJzj5UJMJcOkHKrKH3FuTAWzaQqhkF0o4HylVZP49tgPHxBXBpisga7LeCMI6w

{
    "amount":25000,
    "paymentDate":"2024-08-25",
    "paymentMethod":"UPI",
    "paymentStatus":"Paid"
}