### get all available cars
GET http://localhost:5000/api/customers/cars/available
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBU0VONDEwMCIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc2MTc1ODY2MiwiZXhwIjoxNzYxODQ1MDYyfQ.EE6XHsEylfbvoXcg8E7zEANYeDXOWQx6hMb9kDQTuLI5rRlhPXyUoqrTYE6fhS2JyxUZ7lHKIiCFMX6C60YK7w

### book a car
POST http://localhost:5000/api/customers/booking?userId=3&carId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBU0VONDEwMCIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc2MTc1ODY2MiwiZXhwIjoxNzYxODQ1MDYyfQ.EE6XHsEylfbvoXcg8E7zEANYeDXOWQx6hMb9kDQTuLI5rRlhPXyUoqrTYE6fhS2JyxUZ7lHKIiCFMX6C60YK7w

{
    "rentalStartDate": "2025-06-08 09:30:30",
    "rentalEndDate": "2025-06-09 10:30:30"
}

### get customer bookings
GET http://localhost:5000/api/customers/booking
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lciIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc2MTk3MzcwMiwiZXhwIjoxNzYyMDYwMTAyfQ.1G5gc-koltTAyuYPZsdJJ4uTH1kuT-IM7LkcFdBzz5nUgCDM9XB7skjmnKFQSsDsoum0J22M2Hwu6oYccznNgA